CREATE TABLE IF NOT EXISTS app.todos (
  id UUID NOT NULL DEFAULT uuid_generate_v4(),
  title VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS todos_id_uniq ON app.todos USING BTREE (id);

